name: pycrown
channels:
  - conda-forge
  - conda
dependencies:
  - python>=3.11
  - pip>=10.0
  - numpy>=1.23.2
  - scipy>=1.9.2
  - scikit-image>=0.19.0
  - Cython>=0.29.32
  - numba>=0.56.0
  - pandas>=1.5.0
  - geopandas>=0.12.0
  - Rtree>=0.8.3
  - Fiona>=1.9.0
  - GDAL>=3.5
  - Shapely>=1.6.4
  - rasterio>=1.3.0
  - pyproj>=3.4.0
  - pip:
    - laspy>=2.2.0
